version: '2'
services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=${PGDB}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
